embed links
1Computer1/megumin-selfbot pull request #6
Opened 2017-07-05 04:18 UTC by Darqam

add links to base doc page as well as command link. Note that setTitle was swapped out for setDescription to allow for markup linking.

2017-07-05 23:51 UTC, 1Computer1 requested changes

2017-07-05 23:51 UTC, 1Computer1 commented on src/commands/info/docs.js
> +        let description = `[${mainItem.name}${item.scope === 'static' ? '.' : '#'}${item.name}](https://discord.js.org/#/docs/main/${version}/class/${mainItem.name}${item.scope === 'static' ? '.' : '
These links are incorrect for static members, they look like `scrollTo=s-PROPERTY`

2017-07-06 00:30 UTC, 1Computer1 requested changes

2017-07-06 00:30 UTC, 1Computer1 commented on src/commands/info/docs.js
> +        if (item.description) description += `\r\n${this.clean(item.description)}`;
Why a carriage return here (and in other places)? That's not needed.

2017-07-06 00:30 UTC, 1Computer1 commented on src/commands/info/docs.js
> +            const descript = item.returns.description ? `${this.clean(item.returns.description)}\n` : '';
Change this back to `description` to be consistent with the rest of the methods.

2017-07-06 01:33 UTC, Darqam commented on src/commands/info/docs.js
> +            const descript = item.returns.description ? `${this.clean(item.returns.description)}\n` : '';
The issue with this one is `description` is used in the upper scope on line 84. That was why I changed it to a different word, but maybe I should just change the other descriptions to another term?

2017-07-06 01:34 UTC, 1Computer1 commented on src/commands/info/docs.js
> +            const descript = item.returns.description ? `${this.clean(item.returns.description)}\n` : '';
Oh that is true, `desc` sounds nicer, go with that :P

2017-07-07 02:54 UTC, 1Computer1 approved these changes

2017-07-07 02:57 UTC, merged